version: "3.8"

services:
  db:
    image: postgres:15
    container_name: scheduler_db_container
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: schedule_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scheduler_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: scheduler_backend_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://dev_user:dev_password@db:5432/schedule_db
      PORT: 3000
    depends_on:
      - db
    networks:
      - scheduler_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: scheduler_frontend_container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - scheduler_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: scheduler_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - db
    networks:
      - scheduler_network

volumes:
  postgres_data:

networks:
  scheduler_network:
    driver: bridge
